/**
 * GENERATED by scripts/capture-guide.ts. Do not edit by hand.
 *
 * What each plate's screenshot is, and where the ring goes on it. Boxes are
 * FRACTIONS of the plate (0..1), so the app can draw the ring at any rendered
 * width and in any palette -- see client/src/components/guide/GuideShot.tsx.
 *
 * `Partial`, not a total Record, and the totality is a TEST instead
 * (`tests/guide.test.ts`): a node whose screenshot was never taken renders
 * without a picture rather than refusing to compile, which is what lets the
 * guide's words be written and reviewed before a browser has ever run. The
 * test is what stops that state shipping.
 */
import type { GuidePlateId, GuideShotNodeId } from "./guide";

export type GuideBox = { x: number; y: number; w: number; h: number };

export type GuidePlateImage = {
  /** Served path, under /public/images/guide/. */
  file: string;
  /** The webp's own pixels, so the frame reserves its aspect ratio. */
  width: number;
  height: number;
  capturedAt: string;
};

export const GUIDE_PLATE_IMAGES: Partial<Record<GuidePlateId, GuidePlateImage>> = {
  "character-family": {
    "file": "/public/images/guide/character-family.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:21:02.509Z"
  },
  "character-grown": {
    "file": "/public/images/guide/character-grown.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:21:11.333Z"
  },
  "character-look": {
    "file": "/public/images/guide/character-look.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:21:05.289Z"
  },
  "character-stats": {
    "file": "/public/images/guide/character-stats.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:21:07.949Z"
  },
  "character-tabs": {
    "file": "/public/images/guide/character-tabs.webp",
    "width": 644,
    "height": 338,
    "capturedAt": "2026-09-16T05:21:02.039Z"
  },
  "characters-list": {
    "file": "/public/images/guide/characters-list.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:20:59.618Z"
  },
  "create-top": {
    "file": "/public/images/guide/create-top.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:20:35.679Z"
  },
  "historical": {
    "file": "/public/images/guide/historical.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:20:57.919Z"
  },
  "library": {
    "file": "/public/images/guide/library.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:21:16.003Z"
  },
  "menu": {
    "file": "/public/images/guide/menu.webp",
    "width": 780,
    "height": 1298,
    "capturedAt": "2026-09-16T05:21:35.083Z"
  },
  "origin-cast": {
    "file": "/public/images/guide/origin-cast.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:20:37.688Z"
  },
  "origin-life": {
    "file": "/public/images/guide/origin-life.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:20:50.663Z"
  },
  "origin-prompts": {
    "file": "/public/images/guide/origin-prompts.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:20:53.939Z"
  },
  "origin-quick": {
    "file": "/public/images/guide/origin-quick.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:20:38.141Z"
  },
  "origin-real": {
    "file": "/public/images/guide/origin-real.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:20:49.741Z"
  },
  "origin-series": {
    "file": "/public/images/guide/origin-series.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:20:45.847Z"
  },
  "origin-shared": {
    "file": "/public/images/guide/origin-shared.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:20:40.712Z"
  },
  "origin-story": {
    "file": "/public/images/guide/origin-story.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:20:43.340Z"
  },
  "origin-submit": {
    "file": "/public/images/guide/origin-submit.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:20:54.402Z"
  },
  "origin-tail": {
    "file": "/public/images/guide/origin-tail.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:20:53.493Z"
  },
  "origin-way-in": {
    "file": "/public/images/guide/origin-way-in.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:20:50.203Z"
  },
  "reader-actions": {
    "file": "/public/images/guide/reader-actions.webp",
    "width": 780,
    "height": 64,
    "capturedAt": "2026-09-16T05:21:19.826Z"
  },
  "reader-bar": {
    "file": "/public/images/guide/reader-bar.webp",
    "width": 780,
    "height": 168,
    "capturedAt": "2026-09-16T05:21:19.780Z"
  },
  "reader-extras": {
    "file": "/public/images/guide/reader-extras.webp",
    "width": 780,
    "height": 1182,
    "capturedAt": "2026-09-16T05:21:26.859Z"
  },
  "reader-picking": {
    "file": "/public/images/guide/reader-picking.webp",
    "width": 780,
    "height": 156,
    "capturedAt": "2026-09-16T05:21:23.412Z"
  },
  "settings-parent": {
    "file": "/public/images/guide/settings-parent.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:21:30.912Z"
  },
  "settings-pictures": {
    "file": "/public/images/guide/settings-pictures.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:21:30.447Z"
  },
  "settings-quests": {
    "file": "/public/images/guide/settings-quests.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:21:31.795Z"
  },
  "settings-resets": {
    "file": "/public/images/guide/settings-resets.webp",
    "width": 780,
    "height": 1688,
    "capturedAt": "2026-09-16T05:21:31.357Z"
  },
  "story-top": {
    "file": "/public/images/guide/story-top.webp",
    "width": 780,
    "height": 200,
    "capturedAt": "2026-09-16T05:21:19.699Z"
  }
};

export const GUIDE_BOXES: Partial<Record<GuideShotNodeId, GuideBox>> = {
  "actions": {
    "x": 0,
    "y": 0,
    "w": 1,
    "h": 1
  },
  "alongside": {
    "x": 0.1308,
    "y": 0.564,
    "w": 0.041,
    "h": 0.019
  },
  "appearance": {
    "x": 0.1308,
    "y": 0.3279,
    "w": 0.7385,
    "h": 0.3436
  },
  "cast": {
    "x": 0.0641,
    "y": 0.4763,
    "w": 0.8718,
    "h": 0.0474
  },
  "character-card": {
    "x": 0.0641,
    "y": 0.4147,
    "w": 0.8718,
    "h": 0.3223
  },
  "characters": {
    "x": 0.0641,
    "y": 0.2441,
    "w": 0.4293,
    "h": 0.0474
  },
  "classic": {
    "x": 0.7687,
    "y": 0.0952,
    "w": 0.1894,
    "h": 0.381
  },
  "cliffhanger": {
    "x": 0.0974,
    "y": 0.5355,
    "w": 0.041,
    "h": 0.019
  },
  "continue-story": {
    "x": 0.5925,
    "y": 0.12,
    "w": 0.3767,
    "h": 0.4
  },
  "create": {
    "x": 0.0641,
    "y": 0.2867,
    "w": 0.8718,
    "h": 0.0474
  },
  "dig-into": {
    "x": 0.0641,
    "y": 0.4763,
    "w": 0.8718,
    "h": 0.0474
  },
  "draw-a-picture": {
    "x": 0.1308,
    "y": 0.3279,
    "w": 0.7385,
    "h": 0.045
  },
  "edit-story": {
    "x": 0.255,
    "y": 0,
    "w": 0.1433,
    "h": 1
  },
  "extras": {
    "x": 0.041,
    "y": 0.8203,
    "w": 0.9179,
    "h": 0.1151
  },
  "family": {
    "x": 0.0872,
    "y": 0.3931,
    "w": 0.8256,
    "h": 0.2133
  },
  "favourite": {
    "x": 0.0308,
    "y": 0,
    "w": 0.2139,
    "h": 1
  },
  "focus": {
    "x": 0.7982,
    "y": 0.5238,
    "w": 0.171,
    "h": 0.381
  },
  "font": {
    "x": 0.6154,
    "y": 0.0952,
    "w": 0.143,
    "h": 0.381
  },
  "grown-ups": {
    "x": 0.0872,
    "y": 0.4819,
    "w": 0.8256,
    "h": 0.2986
  },
  "historical": {
    "x": 0.5051,
    "y": 0.2915,
    "w": 0.4205,
    "h": 0.0427
  },
  "how-to-use": {
    "x": 0.0641,
    "y": 0.1114,
    "w": 0.2435,
    "h": 0.0379
  },
  "library": {
    "x": 0.0641,
    "y": 0.3886,
    "w": 0.8718,
    "h": 0.1007
  },
  "make-a-picture": {
    "x": 0.0308,
    "y": 0.5238,
    "w": 0.2927,
    "h": 0.381
  },
  "original": {
    "x": 0.0744,
    "y": 0.2915,
    "w": 0.4205,
    "h": 0.0427
  },
  "palette": {
    "x": 0.2667,
    "y": 0.1429,
    "w": 0.3282,
    "h": 0.2857
  },
  "parent-mode": {
    "x": 0.1051,
    "y": 0.2032,
    "w": 0.7897,
    "h": 0.5924
  },
  "pets": {
    "x": 0.0872,
    "y": 0.63,
    "w": 0.8256,
    "h": 0.2796
  },
  "photo-as-it-is": {
    "x": 0.1308,
    "y": 0.5127,
    "w": 0.7385,
    "h": 0.045
  },
  "photo-to-drawing": {
    "x": 0.1308,
    "y": 0.4108,
    "w": 0.7385,
    "h": 0.045
  },
  "picking": {
    "x": 0.6356,
    "y": 0.2949,
    "w": 0.2388,
    "h": 0.4103
  },
  "picture-settings": {
    "x": 0.1051,
    "y": 0.2672,
    "w": 0.7897,
    "h": 0.4645
  },
  "print-save": {
    "x": 0.5897,
    "y": 0,
    "w": 0.1531,
    "h": 1
  },
  "prompt-editor": {
    "x": 0.5282,
    "y": 0.4787,
    "w": 0.3436,
    "h": 0.0427
  },
  "quest": {
    "x": 0.1308,
    "y": 0.3626,
    "w": 0.041,
    "h": 0.019
  },
  "quest-first-visit": {
    "x": 0.1051,
    "y": 0.2364,
    "w": 0.7897,
    "h": 0.5273
  },
  "quest-length": {
    "x": 0.0641,
    "y": 0.4763,
    "w": 0.8718,
    "h": 0.0474
  },
  "quick-character": {
    "x": 0.0641,
    "y": 0.1919,
    "w": 0.8718,
    "h": 0.6161
  },
  "reader-bar": {
    "x": 0,
    "y": 0,
    "w": 1,
    "h": 1
  },
  "reading-level": {
    "x": 0.0641,
    "y": 0.3389,
    "w": 0.8718,
    "h": 0.0474
  },
  "series": {
    "x": 0.0641,
    "y": 0.3827,
    "w": 0.8718,
    "h": 0.2346
  },
  "share": {
    "x": 0.4085,
    "y": 0,
    "w": 0.171,
    "h": 1
  },
  "shared-story": {
    "x": 0.0641,
    "y": 0.4905,
    "w": 0.041,
    "h": 0.019
  },
  "sheet": {
    "x": 0,
    "y": 0,
    "w": 1,
    "h": 1
  },
  "somewhere-real": {
    "x": 0.7897,
    "y": 0.4858,
    "w": 0.1128,
    "h": 0.0284
  },
  "source": {
    "x": 0.0974,
    "y": 0.6043,
    "w": 0.8051,
    "h": 0.0474
  },
  "start-sheet-again": {
    "x": 0.1051,
    "y": 0.2767,
    "w": 0.7897,
    "h": 0.4467
  },
  "stats": {
    "x": 0.0872,
    "y": 0.1431,
    "w": 0.8256,
    "h": 0.7133
  },
  "story-card": {
    "x": 0.0641,
    "y": 0.5178,
    "w": 0.8718,
    "h": 0.3164
  },
  "story-length": {
    "x": 0.0641,
    "y": 0.4763,
    "w": 0.8718,
    "h": 0.0474
  },
  "story-type": {
    "x": 0.0641,
    "y": 0.6445,
    "w": 0.8718,
    "h": 0.0474
  },
  "text-size": {
    "x": 0.0308,
    "y": 0.0952,
    "w": 0.2154,
    "h": 0.381
  },
  "the-way-in": {
    "x": 0.0974,
    "y": 0.2855,
    "w": 0.8051,
    "h": 0.4289
  },
  "virtue": {
    "x": 0.0641,
    "y": 0.2275,
    "w": 0.8718,
    "h": 0.0474
  },
  "what-should-happen": {
    "x": 0.1103,
    "y": 0.4336,
    "w": 0.7795,
    "h": 0.1327
  },
  "what-to-know": {
    "x": 0.0641,
    "y": 0.6611,
    "w": 0.8718,
    "h": 0.1066
  },
  "where-things-are": {
    "x": 0,
    "y": 0,
    "w": 1,
    "h": 1
  },
  "which-part": {
    "x": 0.0641,
    "y": 0.4763,
    "w": 0.8718,
    "h": 0.0474
  },
  "write-it": {
    "x": 0.0641,
    "y": 0.6232,
    "w": 0.8718,
    "h": 0.0474
  }
};
